In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
## Define the vocabulary size
# convertint to ventors 
voc_size=10000

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [22]:
# One Hot Representation for every word
# words from each sentence is taken out and passed
# 2 params, 1st is words 2nd is vocab size
# list representation
# words representation within 10000 ki window
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4498, 9184, 8571, 105],
 [4498, 9184, 8571, 3273],
 [4498, 9608, 8571, 5965],
 [7256, 9023, 2933, 3654, 6368],
 [7256, 9023, 2933, 3654, 9278],
 [1843, 4498, 6187, 8571, 2043],
 [9736, 1349, 2736, 3654]]

cosince similarity is the concept behind recommendation systems

In [23]:
#word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

# we need to have all sentences of same length

In [29]:
# using pade seq we can set max length to have in each sentence
# for uniformity
# add 0 as prefix or at end as per choice

sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4498 9184 8571  105]
 [   0    0    0    0 4498 9184 8571 3273]
 [   0    0    0    0 4498 9608 8571 5965]
 [   0    0    0 7256 9023 2933 3654 6368]
 [   0    0    0 7256 9023 2933 3654 9278]
 [   0    0    0 1843 4498 6187 8571 2043]
 [   0    0    0    0 9736 1349 2736 3654]]


In [30]:
#feature representation
# wanted 10 features , means 10 dimentions
dim=10

In [53]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
# model.compile('adam','mse')
model.compile(optimizer='adam', loss='mse')
# optimizer adam and loss function mse 

In [56]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [55]:
model.predict(embedded_docs)
# every word is represented in the form of 10 dimentions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 329ms/step


array([[[-0.04380862,  0.023447  , -0.0465029 , -0.01806177,
          0.03817562, -0.03376613, -0.01897475, -0.04503188,
         -0.02041382,  0.04121253],
        [-0.04380862,  0.023447  , -0.0465029 , -0.01806177,
          0.03817562, -0.03376613, -0.01897475, -0.04503188,
         -0.02041382,  0.04121253],
        [-0.04380862,  0.023447  , -0.0465029 , -0.01806177,
          0.03817562, -0.03376613, -0.01897475, -0.04503188,
         -0.02041382,  0.04121253],
        [-0.04380862,  0.023447  , -0.0465029 , -0.01806177,
          0.03817562, -0.03376613, -0.01897475, -0.04503188,
         -0.02041382,  0.04121253],
        [-0.02239733,  0.03167901,  0.01702059, -0.00826738,
         -0.04911734,  0.02053266, -0.03349479,  0.03789074,
         -0.00483631, -0.0058306 ],
        [ 0.00097104, -0.04526502,  0.01838466, -0.03792407,
         -0.0450801 ,  0.017703  , -0.0248062 , -0.00216722,
          0.03526099,  0.04825782],
        [-0.00293181,  0.00067766, -0.00298353,  0.0

In [45]:
embedded_docs[0]
# 1st sentence

array([   0,    0,    0,    0, 4498, 9184, 8571,  105])

In [47]:
# model.predict(embedded_docs[0])
model.predict(np.expand_dims(embedded_docs[0], axis=0))

# np.expand_dims: This adds an additional dimension, converting the shape from (input_length,) to (1, input_length), making it compatible with the model.
# Batch Dimension: Even when predicting a single sequence, the model expects it in a batch format.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step


array([[[-1.8779492e-02,  1.1458635e-02, -2.5243033e-02,  4.0377490e-03,
          3.2124344e-02, -5.2028894e-03,  2.0111803e-02,  1.7745923e-02,
         -8.9015365e-03,  2.9000904e-02],
        [-1.8779492e-02,  1.1458635e-02, -2.5243033e-02,  4.0377490e-03,
          3.2124344e-02, -5.2028894e-03,  2.0111803e-02,  1.7745923e-02,
         -8.9015365e-03,  2.9000904e-02],
        [-1.8779492e-02,  1.1458635e-02, -2.5243033e-02,  4.0377490e-03,
          3.2124344e-02, -5.2028894e-03,  2.0111803e-02,  1.7745923e-02,
         -8.9015365e-03,  2.9000904e-02],
        [-1.8779492e-02,  1.1458635e-02, -2.5243033e-02,  4.0377490e-03,
          3.2124344e-02, -5.2028894e-03,  2.0111803e-02,  1.7745923e-02,
         -8.9015365e-03,  2.9000904e-02],
        [-3.6729775e-02, -4.6963822e-02, -3.3665918e-02,  1.8386293e-02,
          6.1024353e-04,  3.5796165e-03, -2.1640349e-02,  3.7266854e-02,
         -1.6705990e-02,  4.6700407e-02],
        [-1.5205860e-02,  4.1453615e-03, -2.8644299e-02, -2.